name: CI
on: [push]
jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.3
          bundler-cache: true
      - name: Install Imagemagick
        run: |
          wget https://raw.githubusercontent.com/discourse/discourse_docker/main/image/base/install-imagemagick
          chmod +x install-imagemagick
          sudo ./install-imagemagick
      - name: Install gems
        run: bundle install --jobs 4 --retry 3
      - name: Run tests
        run: bundle exec rake test --trace
